config/routes.rb
Rails.application.routes.draw do
  resources :home
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    save_cookie if home_params[:from].present?
    @query = Struct.new(:from, :transfer, :to, :start_time).new(*pick_cookie)

    time_label = [:ym, :dd, :hh, :mn1, :mn2]
    time_value = @query.start_time.split('/').map.with_index{|datetime, index| [time_label[index], datetime] }.to_h
    # TODO 複数候補の対応
    engine = Rails.application.credentials.search_engine
    agent = Mechanize.new
    url = "#{engine[:url]}?#{engine[:from]}=#{@query.from}&#{engine[:transfer]}=#{@query.transfer}&#{engine[:to]}=#{@query.to}&" +
    "Dym=#{time_value[:ym]}&Ddd=#{time_value[:dd]}&Dhh=#{time_value[:hh]}&Dmn1=#{time_value[:mn1]}&Dmn2=#{time_value[:mn2]}&#{engine[:search]}=検索"
    page = agent.get(url)
    p "#{engine[:url]}?#{engine[:from]}=#{@query.from}&#{engine[:transfer]}=#{@query.transfer}&#{engine[:to]}=#{@query.to}&" +
    "Dym=#{time_value[:ym]}&Ddd=#{time_value[:dd]}&Dhh=#{time_value[:hh]}&Dmn1=#{time_value[:mn1]}&Dmn2=#{time_value[:mn2]}&#{engine[:search]}=検索"
# TODO: 経由が徒歩だった時の対応
# TODO: 経由駅が複数候補ある時の対応(山口(山口), 山口(愛知) 新宿, 新宿三丁目 対応)
    structure = File.open("lib/yasuri.yaml"){|f| f.read}
    root = Yasuri.yaml2tree(structure)
    agent = Mechanize.new
    root_page = agent.get(url)
    @routes = root.inject(agent, root_page).map{|hash| hash.deep_transform_keys{|key| key.to_sym}}
    @routes.each do |route|
      arrow = ' → '
      route[:transfers][:station] = route[:transfers][:station].map{|transfer| transfer[:list]}
                                      .unshift(route[:stations][:departure]).push(route[:stations][:arrive])
      route[:overview] = route[:transfers][:station].join(arrow)
      route[:transfers][:time] = route[:transfers][:time].map{|transfer| transfer[:list]}
      route[:transfers][:line] = route[:transfers][:line].map{|transfer| transfer[:list]}
    end
    p @routes
  end

  private
  def pick_cookie
    p cookies[:start_time]
    [cookies[:from], cookies[:transfer], cookies[:to], cookies[:start_time] || Time.now.strftime('%Y%m/%d/%H/%M').insert(-2, '/')]
  end

  def save_cookie
    cookies[:from] = home_params[:from]&.chomp
    cookies[:transfer] = home_params[:transfer]&.chomp
    cookies[:to] = home_params[:to]&.chomp
    cookies[:start_time] = Time.now.strftime('%Y%m/%d/%H/%M').insert(-2, '/')
  end

  def home_params
    params.permit(:from, :transfer, :to)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%= form_with url: home_index_path, method: :get, local: true do |f| %>
  <%= tag.p do %>
    from: <%= f.text_field :from, value: @query.from %>
  <% end %>
  <%= tag.p do %>
    transfer: <%= f.text_field :transfer, value: @query.transfer %>
  <% end %>
  <%= tag.p do %>
    to: <%= f.text_field :to, value: @query.to %>
  <% end %>
  <%= check_box :page, :remember_time, {checked: true} %> remember_time
  <%= select :page, :name, [["", ""], ["", ""]], class: 'datetimepicker' %>
  <%= f.submit 'search' %>
<% end %>

<table>
  <% @routes.each do |route| %>
    <%= tag.tr tag.td route[:title], style: 'background-color: deepskyblue' %>
    <%= tag.tr tag.td route[:overview] %>
    <%= tag.tr tag.td route[:time] %>
    <%= tag.tr do %>
      <%= tag.td do %>
        <%= tag.ul do %>
          <%= route[:transfers][:station].each_cons(2).with_index do |stations, i| %>
            <%= tag.li do %>
              <%= "#{stations.first} → #{stations.last}" %>
              <%= route[:transfers][:time][i] %>
              <%= route[:transfers][:line][i] %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</table>

<script>$('.datetimepicker').datetimepicker();</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCongratulations</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      tr, td {
        border: 1px solid;
      }
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>